/* eslint-disable no-console */
/** @type {import('next').NextConfig} */

/** @module next.config
 *  @since 2023.01.26, 18:09
 *  @changed 2023.03.17, 13:09
 */

const path = require('path');
const withImages = require('next-images');
const fs = require('fs');

const prjPath = path.resolve(__dirname);
const srcPath = path.resolve(prjPath, 'src');

const packageConfig = require(path.resolve(prjPath, 'package.json'));

const { version, timetag, timestamp } = packageConfig;

const nodeEnv = process.env.NODE_ENV;
const isTest = nodeEnv === 'test';
const nextPublicDev = process.env.NEXT_PUBLIC_DEV;
const isDev = !!nextPublicDev;
const isDemo = isDev && nextPublicDev === 'DEMO';
const isDevServer = isDev && nextPublicDev === 'DEVSERVER';
const isProd = !isDev;

const buildType = isDevServer ? 'server' : 'build';
const buildMode = isProd ? 'prod' : 'dev';
const buildTag = [
  // Construct general-purpose build tag
  'v.' + version,
  timetag,
  buildType,
  buildMode,
].join('-');

const envParams = {
  version,
  timetag,
  timestamp,
  buildTag,
  buildType,
  buildMode,
  nodeEnv,
  isTest,
  isDev,
  isDevServer,
  isDemo,
  isProd,
};
// console.log('Environment parameters:', envParams);

// Generate & write scss config (file also will be used for sass-loader below, in `commonCssIncludesFiles`)...
// @see:
// - source: `src/global/css-params-source.js`
// - generated scss: `src/global/css-params-generated.scss`
// - generated js: `src/global/css-params-generated.js`
const cssParamsSourcePath = path.resolve(srcPath, 'global');
const generatedCssParamsPath = path.resolve(srcPath, 'global');
const cssProcessPath = path.resolve(srcPath, 'global/css-params-process');
const generatedCssParamsName = 'css-params-generated';
const generatedCssParamsScssFilename = generatedCssParamsName + '.scss';
const generatedCssParamsJsFilename = generatedCssParamsName + '.js';
const scssGeneratedConfigFile = path.resolve(
  generatedCssParamsPath,
  generatedCssParamsScssFilename,
);
const jsGeneratedConfigFile = path.resolve(generatedCssParamsPath, generatedCssParamsJsFilename);
const cssParamsSourceName = 'css-params-source.js';
const cssParamsSource = require(path.resolve(cssParamsSourcePath, cssParamsSourceName));
const { makeScssConfig, processCssConfigObject } = require(path.resolve(
  cssProcessPath,
  'css-process-routines.js',
));
const cssConfig = processCssConfigObject(cssParamsSource);
// const cssVersion = 'v.' + version + ' / ' + timestamp;
const cssInfoStr = 'Generated by next.config from "' + cssParamsSourceName + '"'; // + ' for ' + cssVersion;
const scssGeneratedConfigContent = makeScssConfig(cssConfig, '// ' + cssInfoStr + '\n\n');
fs.writeFileSync(scssGeneratedConfigFile, scssGeneratedConfigContent);
const jsonData = { INFO: cssInfoStr, ...cssConfig };
const jsonStr = JSON.stringify(jsonData, null, 2);
const jsStr = 'export default ' + jsonStr.replace(/"([A-Za-z_]\w+)":/g, '$1:') + ';';
// fs.writeFileSync(jsonGeneratedConfigFile, jsonStr);
fs.writeFileSync(jsGeneratedConfigFile, jsStr);
// console.log('Generated', scssGeneratedConfigFile);

const nextConfig = {
  /* // svgr (onflicting with withImages)
   * webpack: (config, { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }) => {
   *   // @see https://react-svgr.com/docs/webpack/
   *   // @see https://react-svgr.com/docs/next/
   *   config.module.rules.push({
   *     test: /\.svg$/,
   *     issuer: /\.[jt]sx?$/,
   *     use: ['@svgr/webpack'],
   *   });
   *   return config;
   * },
   */
  reactStrictMode: false, // NOTE: Debug only? It causes double rendering and hooks calling.
  images: {
    unoptimized: true,
    disableStaticImages: true,
  },
  productionBrowserSourceMaps: true,
  env: envParams,
  sassOptions: {
    includePaths: [generatedCssParamsPath],
    prependData:
      '@use "sass:math"; @use "sass:color"; @import "' + generatedCssParamsScssFilename + '";',
  },
};

module.exports = withImages(nextConfig);
// module.exports = nextConfig;
